name: Test with JUnit

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: bitnami/zookeeper
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: yes
        options: >-
          --health-cmd "echo mntr | nc -w 2 -q 2 localhost 2181"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      kafka:
        image: bitnami/kafka
        ports:
          - 9092:9092
        options: >-
          --health-cmd "kafka-broker-api-versions.sh --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          KAFKA_CFG_KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          server-username: ${{secrets.KOTLIN_API_USER}}
          server-password: ${{secrets.KOTLIN_API_TOKEN}}

      - name: Set up Kotlin
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          kotlin-version: '1.8.21'  # Replace with the desired Kotlin version
          username: ${{secrets.KOTLIN_API_USER}}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew build

      - name: Run tests with JUnit
        run: ./gradlew test

      - name: Publish test coverage
        uses: codecov/codecov-action@v2
        with:
          file: build/jacoco/htmlOutput/jacoco-resources
          flags: junit