name: Test with JUnit

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          server-username: ${{secrets.KOTLIN_API_USER}}
          server-password: ${{secrets.KOTLIN_API_TOKEN}}

      - name: Set up Kotlin
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          kotlin-version: '1.8.21'  # Replace with the desired Kotlin version

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build and Test
        run: ./gradlew build

      - name: Run tests with JUnit
        run: ./gradlew test

      - name: Publish test coverage
        uses: codecov/codecov-action@v2
        with:
          file: build/jacoco/htmlOutput/jacoco-resources
          flags: junit