name: Test with JUnit

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: bitnami/zookeeper
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: yes

      kafka:
        image: bitnami/kafka
        ports:
          - 9092:9092

        env:
          KAFKA_ENABLE_KRAFT: no
          KAFKA_CFG_KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          server-username: ${{secrets.KOTLIN_API_USER}}
          server-password: ${{secrets.KOTLIN_API_TOKEN}}

      - name: Set up Kotlin
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          kotlin-version: '1.8.21'  # Replace with the desired Kotlin version
          server-username: ${{secrets.KOTLIN_API_USER}}
          server-password: ${{secrets.KOTLIN_API_TOKEN}}
          # valid inputs are ['java-version', 'java-package', 'architecture', 'jdkFile',
            # 'server-id', 'server-username', 'server-password', 'settings-path',
                      # 'gpg-private-key', 'gpg-passphrase']

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: create Kafka customers topic
        run: bitnami/kafka/bin/kafka-topics.sh --create --topic customers --bootstrap-server kafka:9092 echo "topic customers was created"

      - name: create Kafka orders topic
        run: bitnami/kafka/bin/kafka-topics.sh --create --topic orders --bootstrap-server kafka:9092 echo "topic orders was created"

      - name: create Kafka invoices topic
        run: bitnami/kafka/bin/kafka-topics.sh --create --topic invoices --bootstrap-server kafka:9092 echo "topic invoices was created"

      - name: create Kafka cases topic
        run: bitnami/kafka/bin/kafka-topics.sh --create --topic cases --bootstrap-server kafka:9092 echo "topic cases was created"

      - name: create Kafka statuses topic
        run: bitnami/kafka/bin/kafka-topics.sh --create --topic statuses --bootstrap-server kafka:9092 echo "topic statuses was created"

      - name: create Kafka appearances topic
        run: bitnami/kafka/bin/kafka-topics.sh --create --topic appearances --bootstrap-server kafka:9092 echo "topic appearances was created"

      - name: Build and Test
        run: ./gradlew build

      - name: Publish test coverage
        uses: codecov/codecov-action@v2
        with:
          file: build/jacoco/htmlOutput/jacoco-resources
          flags: junit